[source.vendored-sources]
directory = "../../cargo/vendor"

[source.crates-io]
replace-with = "vendored-sources"

[target.x86_64-unknown-linux-gnu]
rustflags = ['-Clinker=clang', '-Clink-arg=-fuse-ld=lld', '-Clinker-plugin-lto']

[target.aarch64-unknown-linux-gnu]
rustflags = ['-Clinker=clang', '-Clink-arg=-fuse-ld=lld', '-Clinker-plugin-lto']

[target.x86_64-unknown-linux-musl]
rustflags = ['-Ctarget-feature=-crt-static', '-Clinker=clang', '-Clink-arg=-fuse-ld=lld', '-Clink-args=-lunwind']

[target.aarch64-unknown-linux-musl]
rustflags = ['-Ctarget-feature=-crt-static', '-Clinker=clang', '-Clink-arg=-fuse-ld=lld', '-Clink-args=-lunwind']
